# Generated by Django 5.0.4 on 2024-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_payment_payment_id_payment_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='id сессии'),
        ),
    ]
