version: "3"

services:
  db:
    image: postgres:16-alpine
    restart: on-failure
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - pg_data:/D:\PostgreSQL\16\data
    healthcheck:
      test: ["CMD", "-c", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: 4505
      POSTGRES_DB: ${POSTGRES_NAME}

  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "./entrypoint.prod.sh"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  pg_data: